######################################################################
# Automatically generated by qmake (2.01a) Tue Mar 6 20:02:24 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += dice.h dicewindow.h rice.h
SOURCES += dicewindow.cpp main.cpp dice.cpp
RESOURCES += images.qrc
